pipeline {
    agent any

    environment {
        PYTHON_EXE = 'C:\\Users\\mrakh\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
    }

    stages {
        stage('Check Python') {
            steps {
                bat '"%PYTHON_EXE%" --version'
            }
        }

        stage('Setup Python Environment') {
            steps {
                bat '"%PYTHON_EXE%" -m venv venv'
                bat 'venv\\Scripts\\python -m pip install -r backend\\requirements.txt'
            }
        }

        stage('Run Smoke Tests') {
            steps {
                bat 'venv\\Scripts\\python -m pytest -m smoke backend/tests --junitxml=smoke-report.xml'
            }
        }

        stage('Run Regression Tests') {
            steps {
                bat 'venv\\Scripts\\python -m pytest -m regression backend/tests --junitxml=regression-report.xml'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'smoke-report.xml'
                junit 'regression-report.xml'
            }
        }
    }
}